# Site settings
title:          Tristan White
description:    "Tristan White's blog"
# baseurl:        "/tale"
url:            "https://tristanwhite.info"

# Author
author:
  name:         Tristan White
  url:          https://tristanwhite.info
  email:        oliver.tristan@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
# permalink:      /:year-:month-:day/:title
paginate:       5

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
